version: '3.7'
services:
  backend:
    build: ./src
    ports:
      - "8678:8678"
    command: python app/main.py
    tty: true
    volumes:
      - ./src:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .