services:
  backend:
    build: ./src
    ports:
      - "8678:8678"
    command: python app/main.py
    environment:
      - M_PASS=${M_PASS}
      - M_USER=${M_USER}
      - M_HOST=${M_HOST}
    tty: true
    volumes:
      - ./src:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
